config/routes.rb
Rails.application.routes.draw do

  root "blogs#index"
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence:true
  mount_uploader :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
   validates :password, presence: true, length: { minimum: 6 }
   before_validation { email.downcase! }
   has_secure_password
   has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs= Blog.all
    @user = User.all
  end
  def new
    @blog = Blog.new
  end
  def create
    @blog=Blog.new(blog_params)
    @blog=current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
          flash[:success] = 'Post successfully create'
          redirect_to blogs_path
        else
          render :new
      end
    end
  end
  def edit
  end
  def show
  end
  def update
    if @blog.update(blog_params)
    flash[:success] = 'Post successfully update'
    redirect_to blogs_path
  else
    render :edit
  end
  end
  def destroy
    @blog.destroy
    flash[:success] = 'Post successfully destroy'
    redirect_to blogs_path
  end
  def confirm
    @blog=Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end
  private
  def blog_params
    params.require(:blog).permit(:content,:image,:image_cache)
  end
  def set_blog
    @blog=Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash.now[:success] = 'well done!'
      redirect_to user_path(user.id)
    else
      redirect_to new_session_path
      flash[:danger] = 'ooh ! something is wrong'
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:success] = 'good bye'
    redirect_to blogs_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user =User.new
  end
  def create
    @user = User.new(user_params)
    unless @user.save
      render :new
   else
      redirect_to user_path(@user.id)
    end
  end
 def show
   @user =User.find(params[:id])
 end
end
private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name =='edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <% if @blog.errors.any? %>
  <%= @blog.errors.count %> error(s)
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="field">
    <%= form_with(model:@blog,url:choose_new_or_edit,local: true) do |form| %>
        <%= form.text_field :content,:class=>"form-control",
                                      :id=>"exampleInputEmail1" %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
        <div class="actions"><%= form.submit "Post",:class=>"btn btn-primary"%></div>
    <% end %>
</div>
</div>

app/views/blogs/confirm.html.erb
<div class="container">
<h3>Confirm your post</h3>
<%= form_with(model: @blog, url:blogs_path,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url%>
  <%= form.hidden_field :image_cache,:class=>"img-fluid rounded mx-auto d-block",
                                    :alt=>"Responsive image" %>
  <p>Content :<%= @blog.content %> </p>
  <%= form.submit "Confirm" %>
<% end %>
<%= form_with(model:@feed, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <% if logged_in? %>
    <% if @blog.user.id == current_user.id %>
        <%=render 'form' %>
    <% else %>
    <p>Please log in before post new : <span class="badge badge-pill badge-danger"><%= link_to "Log in", new_session_path%></span></p>
    <p>Or Sign Up if you don't have account : <span class="badge badge-pill badge-warning"><%= link_to "Sign Up", new_user_path%></span></p>
   <% end %>
 <% else %>
   <p>Please log in before post new : <span class="badge badge-pill badge-danger"><%= link_to "Log in", new_session_path%></span></p>
   <p>Or Sign Up if you don't have account : <span class="badge badge-pill badge-warning"><%= link_to "Sign Up", new_user_path%></span></p>
 <% end %>
</div>

app/views/blogs/index.html.erb
<div class="container">
<% @blogs.each do |blog| %>
<table class="table">
  <tbody>
    <tr>
      <td><%= blog.user.name %></td>
    </tr>
    <tr>
      <td><%= image_tag blog.image.url,:class=>"img-fluid rounded mx-auto d-block",
                                        :alt=>"Responsive image"%></td>
    </tr>
    <tr>
      <td><%= blog.content%></td>
    </tr>
  <tr class="pill">
   <% if logged_in? %>
      <% if blog.user.id == current_user.id %>
        <td class="badge badge-pill badge-dark"><%= link_to "show", blog_path(blog.id) %></td>
        <td class="badge badge-pill badge-warning"><%= link_to "destroy",blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?'} %></td>
        <td class="badge badge-pill badge-info"><%= link_to "edit", edit_blog_path(blog.id),data: { confirm: 'Are you sure?'} %></td>
     <% else %>
        <td class="badge badge-pill badge-dark"><%= link_to "show", blog_path(blog.id) %></td>
     <% end %>
   <% else %>
       <td class="badge badge-pill badge-dark"><%= link_to "show", blog_path(blog.id) %></td>
   <% end %>
  </tr>
  </tbody>
</table>
<% end %>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <% if logged_in? %>
    <%=render 'form' %>
  <% else %>
    <p>Please log in before post new : <span class="badge badge-pill badge-danger"><%= link_to "Log in", new_session_path%></span></p>
    <p>Or Sign Up if you don't have account : <span class="badge badge-pill badge-warning"><%= link_to "Sign Up", new_user_path%></span></p>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="container">
<table>
  <tbody>
    <tr>
      <td><%=image_tag @blog.image.url%></td>
    </tr>
    <tr>
      <td><%=@blog.content %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
      <% if logged_in? %>
      <ul>
          <li clase="left"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li clase="left"><%= link_to "Logout", session_path(current_user.id), method: :delete %></td>
          <li clase="right"><%= link_to "Home", blogs_path %></li>
          <li clase="right"><%= link_to "new", new_blog_path %></li>
      </ul>
          <% else %>
        <ul>
          <li clase="left"><%= link_to "Sign up", new_user_path%></li>
          <li clase="left"><%= link_to "Login", new_session_path%></li>
          <li clase="right"><%= link_to "Home", blogs_path %></li>
          <li clase="right"><%= link_to "new", new_blog_path %></li>
        </ul>
    <% end%>
    </header>
    <div class="">
      <% flash.each do |key, value|%>
        <%= content_tag(:div,value,class:"alert alert-#{key}")%>
      <% end%>
    </div>
    <%= yield %>

  <footer>
   <p>FacebookClone</p>
   <p>© 2020 DIVE INTO CODE.</p>
 </footer>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h5>Sign up</h5>
   <% if @user.errors.any? %>
   <div id="error_explanation">
   <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
   <ul>
     <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
   </div>
   <% end %>
  <div class="">
    <div class="">
     <%= form_with(model: @user, local: true) do |f| %>
     <%= f.label :name %>
     <%= f.text_field :name,:class=>"form-control",
                            :id=>"exampleInputEmail1" %>
     <%= f.label :email %>
     <%= f.email_field :email,:type=>"email",
                             :class=>"form-control",
                             :id=>"exampleInputEmail1" %>
     <%= f.label :password %>
     <%= f.password_field :password,:type=>"password",
                             :class=>"form-control",
                             :id=>"exampleInputPassword1" %>
     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation,:type=>"password",
                             :class=>"form-control",
                             :id=>"exampleInputPassword1" %>
     <%= f.submit "Create my account",:class=>"btn btn-primary"%>
     <% end %>
     </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h4 class="display-4">Welcomme <%= @user.name %></h4>
    <hr class="my-4">
    <p>Your mail is: <em><%= @user.email %></em>></p>
    <hr class="my-4">
    </div>
</div>